### ISSUE TITLE
扫描结果

### ISSUE THREAD

**Issue by RoziSec** [zongdeiqianxing/Autoscanner#10]
请问一下各个扫描的结果都存储在哪里，用kali安装了环境，扫描结果找不到

**Comment by zongdeiqianxing** [comment]
report目录下，分为两个html文件，tools的和xray
















在 2021-05-10 23:07:12，"Norah C.IV" ***@***.***> 写道：

请问一下各个扫描的结果都存储在哪里，用kali安装了环境，扫描结果找不到

**Comment by RoziSec** [comment]
好的，感谢告知。昨天试了好几次，只有tools的输出结果，今天挂了代理重新试了一下，xray的输出结果已经可以看到了
