### ISSUE TITLE
报错  Name or service not know

### ISSUE THREAD

**Issue by laohuan12138** [zongdeiqianxing/Autoscanner#16]
你好：
    作者
   我在kali linux上安装此软件，全部安装完后运行docker_run.sh文件报Name or service not konw错误
如图所示:
![](https://cdn.laohuan.art/%E6%8D%95%E8%8E%B7.PNG)

后面就什么反应都没了

其中docker_run.sh中指定了域名参数
`docker run -ti --rm -v `pwd`/:/root/ auto:latest -d domain.com`

请问这是什么情况。

**Comment by zongdeiqianxing** [comment]
没遇到过，你是不是docker没有装？？

**Comment by laohuan12138** [comment]
> 没遇到过，你是不是docker没有装？？

是目标域名的问题，域名无法解析就出现这种情况，换个域名就可以

**Comment by zongdeiqianxing** [comment]
嗯嗯 才看到 我刚也复现出来了 后面我会加个判断，谢谢提交
