### ISSUE TITLE
--fu url.txt时报错，请问怎么解决

### ISSUE THREAD

**Issue by h1iba1** [zongdeiqianxing/Autoscanner#2]
root:~/Autoscanner# docker run -ti --rm -v `pwd`/:/root/ autoscanner:latest --fu url.txt
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    main()
  File "main.py", line 20, in main
    arguments = ArgumentParser()
  File "/root/lib/arguments_parse.py", line 18, in __init__
    self.urlList = get_file_content(options.urls_file)
AttributeError: 'Values' object has no attribute 'urls_file'

**Comment by h1iba1** [comment]
将arguments_parse.py18行
self.urlList = get_file_content(options.urls_file)
urls_file改为urlsFile可以解决但是又出现了新的问题。


list index out of range
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    main()
  File "main.py", line 22, in main
    controller.assign_task()
  File "/root/lib/controller.py", line 42, in assign_task
    self.url_scan(http_url)
  File "/root/lib/controller.py", line 49, in url_scan
    if not c.sub_domains:                                        #将crawlergo扫描出的子域名添加到任务清单中
AttributeError: 'Crawlergo' object has no attribute 'sub_domains


同样时--fu url.txt

**Comment by zongdeiqianxing** [comment]
> 将arguments_parse.py18行
> self.urlList = get_file_content(options.urls_file)
> urls_file改为urlsFile可以解决但是又出现了新的问题。
> 
> list index out of range
> Traceback (most recent call last):
> File "main.py", line 25, in
> main()
> File "main.py", line 22, in main
> controller.assign_task()
> File "/root/lib/controller.py", line 42, in assign_task
> self.url_scan(http_url)
> File "/root/lib/controller.py", line 49, in url_scan
> if not c.sub_domains: #将crawlergo扫描出的子域名添加到任务清单中
> AttributeError: 'Crawlergo' object has no attribute 'sub_domains
> 
> 同样时--fu url.txt

已经修改好了，把49行的那个not去掉就好了
有问题的话欢迎再提交
