### ISSUE TITLE
docker搭建容器文件夹permission denied

### ISSUE THREAD

**Issue by youki992** [zongdeiqianxing/Autoscanner#8]
如题，做后正常使用的就只有osscan这个漏扫，其他都无法使用，百度也没有解决这个问题

**Comment by zongdeiqianxing** [comment]
没遇到过 osscan?? 截个图看下吧
















在 2021-03-21 19:07:21，"chobits" ***@***.***> 写道：

如题，做后正常使用的就只有osscan这个漏扫，其他都无法使用，百度也没有解决这个问题

**Comment by youki992** [comment]
> 没遇到过 osscan?? 截个图看下吧 在 2021-03-21 19:07:21，"chobits" ***@***.***> 写道： 如题，做后正常使用的就只有osscan这个漏扫，其他都无法使用，百度也没有解决这个问题 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Sorry，大佬。刚才去下了xray，看了下要chmod 777给运行的漏扫程序，挂载的容器卷才能有权限访问，问题已解决
